config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_path, alert: 'Access denied.' unless @user == current_user
  end
end

app/controllers/visitors_controller.rb
# frozen_string_literal: true

class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.slim
- if user_signed_in?
  li.nav-item= link_to 'Edit account', edit_user_registration_path, class: 'nav-link'
  li.nav-item= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link'
- else
  li.nav-item= link_to 'Sign in', new_user_session_path, class: 'nav-link'
  li.nav-item= link_to 'Sign up', new_user_registration_path, class: 'nav-link'

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 4.0
.container
  nav.navbar.navbar-dark.bg-inverse
    ul.nav.navbar-nav.clearfix
      li.nav-item
        button.navbar-toggler.hidden-sm-up.nav-link aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label=("Toggle navigation") data-target="#exCollapsingNavbar2" data-toggle="collapse" type="button"
          | &#9776;
    #exCollapsingNavbar2.collapse.navbar-toggleable-xs
      = link_to "Rails bootstrap", root_path, class: 'navbar-brand'
      ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
/ add navigation links to this file

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Rails Devise Pundit'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Rails Devise Pundit'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/pages/about.html.slim
- content_for :title do
  | About
h3 About the Website
p
  | This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  | from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/users/_user.html.slim
td= link_to user.email, user

app/views/users/index.html.slim
.container
  .row
    h3 Users
    .column
      table.table
        tbody
          - @users.each do |user|
            tr
              = render user

app/views/users/show.html.slim
h3 User
p
  | Email: #{@user.email if @user.email}
= link_to "Logout", destroy_user_session_path, :method => :delete 

app/views/visitors/index.html.slim
h3 Welcome
p
  = link_to 'Users:', users_path
  = User.count
  | , registered